name: ROS 2 Build and Test Workspace
description: Build and test a ROS 2 workspace from source
author: ICHIRO ITS
branding:
  icon: activity
  color: gray-dark
inputs:
  ros2-distro:
    description: The ROS 2 distribution to be used.
    required: false
    default: iron
runs:
  using: composite
  steps:
    - uses: ichiro-its/ros2-build-and-test-action/setup@d80e4254f5c4722b0dcea1b73b83d434a2db069c
      with:
        ros2-distro: ${{ inputs.ros2-distro }}

    - uses: ichiro-its/ros2-build-and-test-action/build@d80e4254f5c4722b0dcea1b73b83d434a2db069c

    - shell: bash
      run: |
        source install/setup.bash
        colcon test --event-handlers console_cohesion+ --pytest-with-coverage --return-code-on-test-failure
