name: ROS 2 Build and Test Workspace
description: Build and test a ROS 2 workspace from source
author: ICHIRO ITS
branding:
  icon: activity
  color: gray-dark
inputs:
  distro:
    description: The ROS 2 distribution to be used
    required: false
    default: iron
runs:
  using: composite
  steps:
    - uses: ichiro-its/ros2-build-and-test-action/setup@18f8d40805c2668f07b836763824d99bb6e33f9b
      with:
        distro: ${{ inputs.distro }}

    - uses: ichiro-its/ros2-build-and-test-action/build@18f8d40805c2668f07b836763824d99bb6e33f9b

    - shell: bash
      run: |
        source install/setup.bash
        colcon test --event-handlers console_cohesion+ --pytest-with-coverage --return-code-on-test-failure
