name: ROS 2 Workspace Action
description: Setup, build and test a ROS 2 workspace from source
author: ICHIRO ITS
branding:
  icon: activity
  color: gray-dark
inputs:
  distro:
    description: The ROS 2 distribution to be used
    required: false
    default: iron
runs:
  using: composite
  steps:
    - uses: ichiro-its/ros2-ws-action/setup@18f8d40805c2668f07b836763824d99bb6e33f9b
      with:
        distro: ${{ inputs.distro }}

    - uses: ichiro-its/ros2-ws-action/build@18f8d40805c2668f07b836763824d99bb6e33f9b

    - uses: ichiro-its/ros2-ws-action/test@3aa0cc0847b20cb0b907952964d5c4e3594c1924
