name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [humble, iron]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Checkout ROS 2 examples on non master branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ros2/examples
          ref: ${{ matrix.ros2-distro }}
          path: examples

      - name: Only test some packages
        run: |
          mv examples/rclcpp/topics cpptopics
          mv examples/rclpy/topics pytopics
          rm -rf examples test

      - name: Test the action
        uses: ./
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

      - name: Upload build result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Install
          path: install

  failed-build:
    name: Failed Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Only test some packages
        run: |
          mv test/failed_build failed_build
          rm -rf examples test

      - name: Test the action
        id: action
        continue-on-error: true
        uses: ./

      - name: Fails if previous step has succeeded
        if: ${{ steps.action.outcome == 'success' }}
        run: false

  failed-test:
    name: Failed Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Only test some packages
        run: |
          mv test/failed_test failed_test
          rm -rf examples test

      - name: Test the action
        id: action
        continue-on-error: true
        uses: ./

      - name: Fails if previous step has succeeded
        if: ${{ steps.action.outcome == 'success' }}
        run: false
