name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  individual-setup-build:
    name: Individual Setup and build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [humble, iron]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: ${{ matrix.ros2-distro }}
          path: examples
          sparse-checkout: |
            rclcpp/topics
            rclpy/topics

      - name: Setup workspace
        uses: ./setup
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

      - name: Build workspace
        uses: ./build
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

  setup-build-test:
    name: Setup, Build, and Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [humble, iron]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples on non master branch
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: ${{ matrix.ros2-distro }}
          path: examples
          sparse-checkout: |
            rclcpp/topics
            rclpy/topics

      - name: Test the action
        uses: ./
        with:
          ros2-distro: ${{ matrix.ros2-distro }}
