name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [humble, iron]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: ${{ matrix.ros2-distro }}
          path: examples
          sparse-checkout: |
            rclcpp/topics
            rclpy/topics

      - name: Setup workspace
        uses: ./setup
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros2-distro: [humble, iron]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples on non master branch
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: ${{ matrix.ros2-distro }}
          path: examples
          sparse-checkout: |
            rclcpp/topics
            rclpy/topics

      - name: Test the action
        uses: ./
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

      - name: Upload build result
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Install
          path: install

  failed-build:
    name: Failed Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: iron
          path: examples
          sparse-checkout: rclcpp/topics/minimal_publisher

      - name: Adjust packages
        run: rm examples/rclcpp/topics/minimal_publisher/lambda.cpp

      - name: Test the action
        id: action
        continue-on-error: true
        uses: ./

      - name: Fails if previous step has succeeded
        if: ${{ steps.action.outcome == 'success' }}
        run: false

  failed-test:
    name: Failed Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.1

      - name: Checkout ROS 2 examples
        uses: actions/checkout@v4.1.1
        with:
          repository: ros2/examples
          ref: iron
          path: examples
          sparse-checkout: rclcpp/topics/minimal_publisher

      - name: Adjust packages
        run: sed -i 's/return 0;/int unused   ;;;; return 0;/g' examples/rclcpp/topics/minimal_publisher/lambda.cpp

      - name: Test the action
        id: action
        continue-on-error: true
        uses: ./

      - name: Fails if previous step has succeeded
        if: ${{ steps.action.outcome == 'success' }}
        run: false
